version: "3.8"

services:
  frontend:
    container_name: perfume-frontend
    build:
      context: .
      args:
        NEXT_PUBLIC_BACKEND_BASE_URL: ${NEXT_PUBLIC_BACKEND_BASE_URL:-http://localhost:8000}
    env_file:
      - .env.local
    environment:
      NEXT_PUBLIC_BACKEND_BASE_URL: ${NEXT_PUBLIC_BACKEND_BASE_URL:-http://localhost:8000}
    ports:
      - "3000:3000"
    restart: always
